build:
	docker build -t krystism/videosynopsis .
run:
	docker run -t -i --rm --name videosynopsis krystism/videosynopsis
push:
	docker build -t localhost:5000/videosynopsis .
	docker push localhost:5000/videosynopsis
